FROM docker:17.11.0-ce-git

LABEL maintainer="Jakub Kaczmarzyk <jakubk@mit.edu>"

COPY requirements.txt requirements-dev.txt /opt/neurodocker/

RUN tmp_pkgs="gcc musl-dev python3-dev sqlite-dev" \
    && apk add --update --no-cache python3 rsync $tmp_pkgs \
    && pip3 install --no-cache-dir -r /opt/neurodocker/requirements.txt \
    && pip3 install --no-cache-dir -r /opt/neurodocker/requirements-dev.txt \
    && pip3 install --no-cache-dir reprozip \
    && apk del $tmp_pkgs
